<?php
/**
 * ShipmentExceptionsApi
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Arta Public API
 *
 * The Arta Public API provides quote generation, transport booking, and tracking capabilities. Additionally the API enables Arta partner organizations to configure email and webhook notifications for their accounts.
 *
 * The version of the OpenAPI document: 2021-01-01
 * Contact: hello@arta.io
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.1.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use OpenAPI\Client\ApiException;
use OpenAPI\Client\Configuration;
use OpenAPI\Client\HeaderSelector;
use OpenAPI\Client\ObjectSerializer;

/**
 * ShipmentExceptionsApi Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ShipmentExceptionsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'shipmentExceptionsCreate' => [
            'application/json',
        ],
        'shipmentExceptionsGet' => [
            'application/json',
        ],
        'shipmentExceptionsList' => [
            'application/json',
        ],
        'shipmentExceptionsUpdate' => [
            'application/json',
        ],
    ];

/**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation shipmentExceptionsCreate
     *
     * Create Shipment Exception
     *
     * @param  string $authorization Authorize your API calls with an Arta API token (required)
     * @param  \OpenAPI\Client\Model\ShipmentExceptionsCreateRequest $shipment_exceptions_create_request shipment_exceptions_create_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['shipmentExceptionsCreate'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\ShipmentExceptionsCreate201Response
     */
    public function shipmentExceptionsCreate($authorization, $shipment_exceptions_create_request = null, string $contentType = self::contentTypes['shipmentExceptionsCreate'][0])
    {
        list($response) = $this->shipmentExceptionsCreateWithHttpInfo($authorization, $shipment_exceptions_create_request, $contentType);
        return $response;
    }

    /**
     * Operation shipmentExceptionsCreateWithHttpInfo
     *
     * Create Shipment Exception
     *
     * @param  string $authorization Authorize your API calls with an Arta API token (required)
     * @param  \OpenAPI\Client\Model\ShipmentExceptionsCreateRequest $shipment_exceptions_create_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['shipmentExceptionsCreate'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\ShipmentExceptionsCreate201Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function shipmentExceptionsCreateWithHttpInfo($authorization, $shipment_exceptions_create_request = null, string $contentType = self::contentTypes['shipmentExceptionsCreate'][0])
    {
        $request = $this->shipmentExceptionsCreateRequest($authorization, $shipment_exceptions_create_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 201:
                    if ('\OpenAPI\Client\Model\ShipmentExceptionsCreate201Response' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Model\ShipmentExceptionsCreate201Response' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                 );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\ShipmentExceptionsCreate201Response', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\OpenAPI\Client\Model\ShipmentExceptionsCreate201Response';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 201:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\ShipmentExceptionsCreate201Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation shipmentExceptionsCreateAsync
     *
     * Create Shipment Exception
     *
     * @param  string $authorization Authorize your API calls with an Arta API token (required)
     * @param  \OpenAPI\Client\Model\ShipmentExceptionsCreateRequest $shipment_exceptions_create_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['shipmentExceptionsCreate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function shipmentExceptionsCreateAsync($authorization, $shipment_exceptions_create_request = null, string $contentType = self::contentTypes['shipmentExceptionsCreate'][0])
    {
        return $this->shipmentExceptionsCreateAsyncWithHttpInfo($authorization, $shipment_exceptions_create_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation shipmentExceptionsCreateAsyncWithHttpInfo
     *
     * Create Shipment Exception
     *
     * @param  string $authorization Authorize your API calls with an Arta API token (required)
     * @param  \OpenAPI\Client\Model\ShipmentExceptionsCreateRequest $shipment_exceptions_create_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['shipmentExceptionsCreate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function shipmentExceptionsCreateAsyncWithHttpInfo($authorization, $shipment_exceptions_create_request = null, string $contentType = self::contentTypes['shipmentExceptionsCreate'][0])
    {
        $returnType = '\OpenAPI\Client\Model\ShipmentExceptionsCreate201Response';
        $request = $this->shipmentExceptionsCreateRequest($authorization, $shipment_exceptions_create_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'shipmentExceptionsCreate'
     *
     * @param  string $authorization Authorize your API calls with an Arta API token (required)
     * @param  \OpenAPI\Client\Model\ShipmentExceptionsCreateRequest $shipment_exceptions_create_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['shipmentExceptionsCreate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function shipmentExceptionsCreateRequest($authorization, $shipment_exceptions_create_request = null, string $contentType = self::contentTypes['shipmentExceptionsCreate'][0])
    {

        // verify the required parameter 'authorization' is set
        if ($authorization === null || (is_array($authorization) && count($authorization) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $authorization when calling shipmentExceptionsCreate'
            );
        }



        $resourcePath = '/shipment_exceptions';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($authorization !== null) {
            $headerParams['Authorization'] = ObjectSerializer::toHeaderValue($authorization);
        }



        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($shipment_exceptions_create_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($shipment_exceptions_create_request));
            } else {
                $httpBody = $shipment_exceptions_create_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation shipmentExceptionsGet
     *
     * Get a Shipment Exception
     *
     * @param  string $authorization Authorize your API calls with an Arta API token (required)
     * @param  string $shipment_exception_id shipment_exception_id parameter (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['shipmentExceptionsGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\ShipmentExceptionsGet200Response|\OpenAPI\Client\Model\BasicError
     */
    public function shipmentExceptionsGet($authorization, $shipment_exception_id, string $contentType = self::contentTypes['shipmentExceptionsGet'][0])
    {
        list($response) = $this->shipmentExceptionsGetWithHttpInfo($authorization, $shipment_exception_id, $contentType);
        return $response;
    }

    /**
     * Operation shipmentExceptionsGetWithHttpInfo
     *
     * Get a Shipment Exception
     *
     * @param  string $authorization Authorize your API calls with an Arta API token (required)
     * @param  string $shipment_exception_id shipment_exception_id parameter (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['shipmentExceptionsGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\ShipmentExceptionsGet200Response|\OpenAPI\Client\Model\BasicError, HTTP status code, HTTP response headers (array of strings)
     */
    public function shipmentExceptionsGetWithHttpInfo($authorization, $shipment_exception_id, string $contentType = self::contentTypes['shipmentExceptionsGet'][0])
    {
        $request = $this->shipmentExceptionsGetRequest($authorization, $shipment_exception_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\OpenAPI\Client\Model\ShipmentExceptionsGet200Response' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Model\ShipmentExceptionsGet200Response' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                 );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\ShipmentExceptionsGet200Response', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 404:
                    if ('\OpenAPI\Client\Model\BasicError' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Model\BasicError' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                 );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\BasicError', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\OpenAPI\Client\Model\ShipmentExceptionsGet200Response';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\ShipmentExceptionsGet200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\BasicError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation shipmentExceptionsGetAsync
     *
     * Get a Shipment Exception
     *
     * @param  string $authorization Authorize your API calls with an Arta API token (required)
     * @param  string $shipment_exception_id shipment_exception_id parameter (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['shipmentExceptionsGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function shipmentExceptionsGetAsync($authorization, $shipment_exception_id, string $contentType = self::contentTypes['shipmentExceptionsGet'][0])
    {
        return $this->shipmentExceptionsGetAsyncWithHttpInfo($authorization, $shipment_exception_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation shipmentExceptionsGetAsyncWithHttpInfo
     *
     * Get a Shipment Exception
     *
     * @param  string $authorization Authorize your API calls with an Arta API token (required)
     * @param  string $shipment_exception_id shipment_exception_id parameter (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['shipmentExceptionsGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function shipmentExceptionsGetAsyncWithHttpInfo($authorization, $shipment_exception_id, string $contentType = self::contentTypes['shipmentExceptionsGet'][0])
    {
        $returnType = '\OpenAPI\Client\Model\ShipmentExceptionsGet200Response';
        $request = $this->shipmentExceptionsGetRequest($authorization, $shipment_exception_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'shipmentExceptionsGet'
     *
     * @param  string $authorization Authorize your API calls with an Arta API token (required)
     * @param  string $shipment_exception_id shipment_exception_id parameter (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['shipmentExceptionsGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function shipmentExceptionsGetRequest($authorization, $shipment_exception_id, string $contentType = self::contentTypes['shipmentExceptionsGet'][0])
    {

        // verify the required parameter 'authorization' is set
        if ($authorization === null || (is_array($authorization) && count($authorization) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $authorization when calling shipmentExceptionsGet'
            );
        }

        // verify the required parameter 'shipment_exception_id' is set
        if ($shipment_exception_id === null || (is_array($shipment_exception_id) && count($shipment_exception_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $shipment_exception_id when calling shipmentExceptionsGet'
            );
        }


        $resourcePath = '/shipment_exceptions/{shipment_exception_id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($authorization !== null) {
            $headerParams['Authorization'] = ObjectSerializer::toHeaderValue($authorization);
        }

        // path params
        if ($shipment_exception_id !== null) {
            $resourcePath = str_replace(
                '{' . 'shipment_exception_id' . '}',
                ObjectSerializer::toPathValue($shipment_exception_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation shipmentExceptionsList
     *
     * List Shipment Exceptions
     *
     * @param  string $authorization Authorize your API calls with an Arta API token (required)
     * @param  int $page_size Results per page (max 50) (optional, default to 20)
     * @param  int $page Page number of the results to fetch. (optional, default to 1)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['shipmentExceptionsList'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\ShipmentExceptionsList200Response
     */
    public function shipmentExceptionsList($authorization, $page_size = 20, $page = 1, string $contentType = self::contentTypes['shipmentExceptionsList'][0])
    {
        list($response) = $this->shipmentExceptionsListWithHttpInfo($authorization, $page_size, $page, $contentType);
        return $response;
    }

    /**
     * Operation shipmentExceptionsListWithHttpInfo
     *
     * List Shipment Exceptions
     *
     * @param  string $authorization Authorize your API calls with an Arta API token (required)
     * @param  int $page_size Results per page (max 50) (optional, default to 20)
     * @param  int $page Page number of the results to fetch. (optional, default to 1)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['shipmentExceptionsList'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\ShipmentExceptionsList200Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function shipmentExceptionsListWithHttpInfo($authorization, $page_size = 20, $page = 1, string $contentType = self::contentTypes['shipmentExceptionsList'][0])
    {
        $request = $this->shipmentExceptionsListRequest($authorization, $page_size, $page, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\OpenAPI\Client\Model\ShipmentExceptionsList200Response' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Model\ShipmentExceptionsList200Response' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                 );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\ShipmentExceptionsList200Response', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\OpenAPI\Client\Model\ShipmentExceptionsList200Response';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\ShipmentExceptionsList200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation shipmentExceptionsListAsync
     *
     * List Shipment Exceptions
     *
     * @param  string $authorization Authorize your API calls with an Arta API token (required)
     * @param  int $page_size Results per page (max 50) (optional, default to 20)
     * @param  int $page Page number of the results to fetch. (optional, default to 1)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['shipmentExceptionsList'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function shipmentExceptionsListAsync($authorization, $page_size = 20, $page = 1, string $contentType = self::contentTypes['shipmentExceptionsList'][0])
    {
        return $this->shipmentExceptionsListAsyncWithHttpInfo($authorization, $page_size, $page, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation shipmentExceptionsListAsyncWithHttpInfo
     *
     * List Shipment Exceptions
     *
     * @param  string $authorization Authorize your API calls with an Arta API token (required)
     * @param  int $page_size Results per page (max 50) (optional, default to 20)
     * @param  int $page Page number of the results to fetch. (optional, default to 1)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['shipmentExceptionsList'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function shipmentExceptionsListAsyncWithHttpInfo($authorization, $page_size = 20, $page = 1, string $contentType = self::contentTypes['shipmentExceptionsList'][0])
    {
        $returnType = '\OpenAPI\Client\Model\ShipmentExceptionsList200Response';
        $request = $this->shipmentExceptionsListRequest($authorization, $page_size, $page, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'shipmentExceptionsList'
     *
     * @param  string $authorization Authorize your API calls with an Arta API token (required)
     * @param  int $page_size Results per page (max 50) (optional, default to 20)
     * @param  int $page Page number of the results to fetch. (optional, default to 1)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['shipmentExceptionsList'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function shipmentExceptionsListRequest($authorization, $page_size = 20, $page = 1, string $contentType = self::contentTypes['shipmentExceptionsList'][0])
    {

        // verify the required parameter 'authorization' is set
        if ($authorization === null || (is_array($authorization) && count($authorization) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $authorization when calling shipmentExceptionsList'
            );
        }




        $resourcePath = '/shipment_exceptions';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page_size,
            'page_size', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page,
            'page', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);

        // header params
        if ($authorization !== null) {
            $headerParams['Authorization'] = ObjectSerializer::toHeaderValue($authorization);
        }



        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation shipmentExceptionsUpdate
     *
     * Update a Shipment Exception
     *
     * @param  string $authorization Authorize your API calls with an Arta API token (required)
     * @param  string $shipment_exception_id shipment_exception_id parameter (required)
     * @param  \OpenAPI\Client\Model\ShipmentExceptionsUpdateRequest $shipment_exceptions_update_request shipment_exceptions_update_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['shipmentExceptionsUpdate'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\ShipmentExceptionsUpdate200Response
     */
    public function shipmentExceptionsUpdate($authorization, $shipment_exception_id, $shipment_exceptions_update_request = null, string $contentType = self::contentTypes['shipmentExceptionsUpdate'][0])
    {
        list($response) = $this->shipmentExceptionsUpdateWithHttpInfo($authorization, $shipment_exception_id, $shipment_exceptions_update_request, $contentType);
        return $response;
    }

    /**
     * Operation shipmentExceptionsUpdateWithHttpInfo
     *
     * Update a Shipment Exception
     *
     * @param  string $authorization Authorize your API calls with an Arta API token (required)
     * @param  string $shipment_exception_id shipment_exception_id parameter (required)
     * @param  \OpenAPI\Client\Model\ShipmentExceptionsUpdateRequest $shipment_exceptions_update_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['shipmentExceptionsUpdate'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\ShipmentExceptionsUpdate200Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function shipmentExceptionsUpdateWithHttpInfo($authorization, $shipment_exception_id, $shipment_exceptions_update_request = null, string $contentType = self::contentTypes['shipmentExceptionsUpdate'][0])
    {
        $request = $this->shipmentExceptionsUpdateRequest($authorization, $shipment_exception_id, $shipment_exceptions_update_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\OpenAPI\Client\Model\ShipmentExceptionsUpdate200Response' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Model\ShipmentExceptionsUpdate200Response' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                 );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\ShipmentExceptionsUpdate200Response', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\OpenAPI\Client\Model\ShipmentExceptionsUpdate200Response';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\ShipmentExceptionsUpdate200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation shipmentExceptionsUpdateAsync
     *
     * Update a Shipment Exception
     *
     * @param  string $authorization Authorize your API calls with an Arta API token (required)
     * @param  string $shipment_exception_id shipment_exception_id parameter (required)
     * @param  \OpenAPI\Client\Model\ShipmentExceptionsUpdateRequest $shipment_exceptions_update_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['shipmentExceptionsUpdate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function shipmentExceptionsUpdateAsync($authorization, $shipment_exception_id, $shipment_exceptions_update_request = null, string $contentType = self::contentTypes['shipmentExceptionsUpdate'][0])
    {
        return $this->shipmentExceptionsUpdateAsyncWithHttpInfo($authorization, $shipment_exception_id, $shipment_exceptions_update_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation shipmentExceptionsUpdateAsyncWithHttpInfo
     *
     * Update a Shipment Exception
     *
     * @param  string $authorization Authorize your API calls with an Arta API token (required)
     * @param  string $shipment_exception_id shipment_exception_id parameter (required)
     * @param  \OpenAPI\Client\Model\ShipmentExceptionsUpdateRequest $shipment_exceptions_update_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['shipmentExceptionsUpdate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function shipmentExceptionsUpdateAsyncWithHttpInfo($authorization, $shipment_exception_id, $shipment_exceptions_update_request = null, string $contentType = self::contentTypes['shipmentExceptionsUpdate'][0])
    {
        $returnType = '\OpenAPI\Client\Model\ShipmentExceptionsUpdate200Response';
        $request = $this->shipmentExceptionsUpdateRequest($authorization, $shipment_exception_id, $shipment_exceptions_update_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'shipmentExceptionsUpdate'
     *
     * @param  string $authorization Authorize your API calls with an Arta API token (required)
     * @param  string $shipment_exception_id shipment_exception_id parameter (required)
     * @param  \OpenAPI\Client\Model\ShipmentExceptionsUpdateRequest $shipment_exceptions_update_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['shipmentExceptionsUpdate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function shipmentExceptionsUpdateRequest($authorization, $shipment_exception_id, $shipment_exceptions_update_request = null, string $contentType = self::contentTypes['shipmentExceptionsUpdate'][0])
    {

        // verify the required parameter 'authorization' is set
        if ($authorization === null || (is_array($authorization) && count($authorization) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $authorization when calling shipmentExceptionsUpdate'
            );
        }

        // verify the required parameter 'shipment_exception_id' is set
        if ($shipment_exception_id === null || (is_array($shipment_exception_id) && count($shipment_exception_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $shipment_exception_id when calling shipmentExceptionsUpdate'
            );
        }



        $resourcePath = '/shipment_exceptions/{shipment_exception_id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($authorization !== null) {
            $headerParams['Authorization'] = ObjectSerializer::toHeaderValue($authorization);
        }

        // path params
        if ($shipment_exception_id !== null) {
            $resourcePath = str_replace(
                '{' . 'shipment_exception_id' . '}',
                ObjectSerializer::toPathValue($shipment_exception_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($shipment_exceptions_update_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($shipment_exceptions_update_request));
            } else {
                $httpBody = $shipment_exceptions_update_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PATCH',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
