<?php
/**
 * RequestListItemsInner
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Arta\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Arta Public API
 *
 * The Arta Public API provides quote generation, transport booking, and tracking capabilities. Additionally the API enables Arta partner organizations to configure email and webhook notifications for their accounts.
 *
 * The version of the OpenAPI document: 2021-01-01
 * Contact: hello@arta.io
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.1.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Arta\Client\Model;

use \ArrayAccess;
use \Arta\Client\ObjectSerializer;

/**
 * RequestListItemsInner Class Doc Comment
 *
 * @category Class
 * @package  Arta\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class RequestListItemsInner implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'requestList_items_inner';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'bookable' => '\Arta\Client\Model\RequestListItemsInnerBookable',
        'created_at' => 'string',
        'destination' => '\Arta\Client\Model\RequestListItemsInnerDestination',
        'hosted_session_id' => 'int',
        'id' => 'string',
        'insurance' => 'string',
        'internal_reference' => 'string',
        'log_request_id' => 'string',
        'object_count' => 'int',
        'origin' => '\Arta\Client\Model\RequestListItemsInnerOrigin',
        'public_reference' => 'string',
        'quote_types' => 'string[]',
        'shortcode' => 'string',
        'status' => 'string',
        'updated_at' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'bookable' => null,
        'created_at' => null,
        'destination' => null,
        'hosted_session_id' => null,
        'id' => null,
        'insurance' => null,
        'internal_reference' => null,
        'log_request_id' => null,
        'object_count' => null,
        'origin' => null,
        'public_reference' => null,
        'quote_types' => null,
        'shortcode' => null,
        'status' => null,
        'updated_at' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'bookable' => false,
		'created_at' => false,
		'destination' => false,
		'hosted_session_id' => true,
		'id' => false,
		'insurance' => true,
		'internal_reference' => true,
		'log_request_id' => true,
		'object_count' => false,
		'origin' => false,
		'public_reference' => true,
		'quote_types' => false,
		'shortcode' => false,
		'status' => false,
		'updated_at' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'bookable' => 'bookable',
        'created_at' => 'created_at',
        'destination' => 'destination',
        'hosted_session_id' => 'hosted_session_id',
        'id' => 'id',
        'insurance' => 'insurance',
        'internal_reference' => 'internal_reference',
        'log_request_id' => 'log_request_id',
        'object_count' => 'object_count',
        'origin' => 'origin',
        'public_reference' => 'public_reference',
        'quote_types' => 'quote_types',
        'shortcode' => 'shortcode',
        'status' => 'status',
        'updated_at' => 'updated_at'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'bookable' => 'setBookable',
        'created_at' => 'setCreatedAt',
        'destination' => 'setDestination',
        'hosted_session_id' => 'setHostedSessionId',
        'id' => 'setId',
        'insurance' => 'setInsurance',
        'internal_reference' => 'setInternalReference',
        'log_request_id' => 'setLogRequestId',
        'object_count' => 'setObjectCount',
        'origin' => 'setOrigin',
        'public_reference' => 'setPublicReference',
        'quote_types' => 'setQuoteTypes',
        'shortcode' => 'setShortcode',
        'status' => 'setStatus',
        'updated_at' => 'setUpdatedAt'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'bookable' => 'getBookable',
        'created_at' => 'getCreatedAt',
        'destination' => 'getDestination',
        'hosted_session_id' => 'getHostedSessionId',
        'id' => 'getId',
        'insurance' => 'getInsurance',
        'internal_reference' => 'getInternalReference',
        'log_request_id' => 'getLogRequestId',
        'object_count' => 'getObjectCount',
        'origin' => 'getOrigin',
        'public_reference' => 'getPublicReference',
        'quote_types' => 'getQuoteTypes',
        'shortcode' => 'getShortcode',
        'status' => 'getStatus',
        'updated_at' => 'getUpdatedAt'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const INSURANCE_NULL = 'null';
    public const INSURANCE_ARTA_TRANSIT_INSURANCE = 'arta_transit_insurance';
    public const QUOTE_TYPES_PARCEL = 'parcel';
    public const QUOTE_TYPES_PREMIUM = 'premium';
    public const QUOTE_TYPES_SELECT = 'select';
    public const QUOTE_TYPES_SELF_SHIP = 'self_ship';
    public const STATUS_QUOTED = 'quoted';
    public const STATUS_IN_PROGRESS = 'in_progress';
    public const STATUS_CLOSED = 'closed';
    public const STATUS_DISQUALIFIED = 'disqualified';
    public const STATUS_EXPIRED = 'expired';
    public const STATUS_CANCELLED = 'cancelled';
    public const STATUS_PENDING = 'pending';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getInsuranceAllowableValues()
    {
        return [
            self::INSURANCE_NULL,
            self::INSURANCE_ARTA_TRANSIT_INSURANCE,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getQuoteTypesAllowableValues()
    {
        return [
            self::QUOTE_TYPES_PARCEL,
            self::QUOTE_TYPES_PREMIUM,
            self::QUOTE_TYPES_SELECT,
            self::QUOTE_TYPES_SELF_SHIP,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getStatusAllowableValues()
    {
        return [
            self::STATUS_QUOTED,
            self::STATUS_IN_PROGRESS,
            self::STATUS_CLOSED,
            self::STATUS_DISQUALIFIED,
            self::STATUS_EXPIRED,
            self::STATUS_CANCELLED,
            self::STATUS_PENDING,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('bookable', $data ?? [], null);
        $this->setIfExists('created_at', $data ?? [], null);
        $this->setIfExists('destination', $data ?? [], null);
        $this->setIfExists('hosted_session_id', $data ?? [], null);
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('insurance', $data ?? [], null);
        $this->setIfExists('internal_reference', $data ?? [], null);
        $this->setIfExists('log_request_id', $data ?? [], null);
        $this->setIfExists('object_count', $data ?? [], null);
        $this->setIfExists('origin', $data ?? [], null);
        $this->setIfExists('public_reference', $data ?? [], null);
        $this->setIfExists('quote_types', $data ?? [], null);
        $this->setIfExists('shortcode', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('updated_at', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getInsuranceAllowableValues();
        if (!is_null($this->container['insurance']) && !in_array($this->container['insurance'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'insurance', must be one of '%s'",
                $this->container['insurance'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getStatusAllowableValues();
        if (!is_null($this->container['status']) && !in_array($this->container['status'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'status', must be one of '%s'",
                $this->container['status'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets bookable
     *
     * @return \Arta\Client\Model\RequestListItemsInnerBookable|null
     */
    public function getBookable()
    {
        return $this->container['bookable'];
    }

    /**
     * Sets bookable
     *
     * @param \Arta\Client\Model\RequestListItemsInnerBookable|null $bookable bookable
     *
     * @return self
     */
    public function setBookable($bookable)
    {
        if (is_null($bookable)) {
            throw new \InvalidArgumentException('non-nullable bookable cannot be null');
        }
        $this->container['bookable'] = $bookable;

        return $this;
    }

    /**
     * Gets created_at
     *
     * @return string|null
     */
    public function getCreatedAt()
    {
        return $this->container['created_at'];
    }

    /**
     * Sets created_at
     *
     * @param string|null $created_at A NaiveDatetime-formatted timestamp describing when the resource was created with microsecond precision
     *
     * @return self
     */
    public function setCreatedAt($created_at)
    {
        if (is_null($created_at)) {
            throw new \InvalidArgumentException('non-nullable created_at cannot be null');
        }
        $this->container['created_at'] = $created_at;

        return $this;
    }

    /**
     * Gets destination
     *
     * @return \Arta\Client\Model\RequestListItemsInnerDestination|null
     */
    public function getDestination()
    {
        return $this->container['destination'];
    }

    /**
     * Sets destination
     *
     * @param \Arta\Client\Model\RequestListItemsInnerDestination|null $destination destination
     *
     * @return self
     */
    public function setDestination($destination)
    {
        if (is_null($destination)) {
            throw new \InvalidArgumentException('non-nullable destination cannot be null');
        }
        $this->container['destination'] = $destination;

        return $this;
    }

    /**
     * Gets hosted_session_id
     *
     * @return int|null
     */
    public function getHostedSessionId()
    {
        return $this->container['hosted_session_id'];
    }

    /**
     * Sets hosted_session_id
     *
     * @param int|null $hosted_session_id The ID of the HostedSession through which this request was created
     *
     * @return self
     */
    public function setHostedSessionId($hosted_session_id)
    {
        if (is_null($hosted_session_id)) {
            array_push($this->openAPINullablesSetToNull, 'hosted_session_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('hosted_session_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['hosted_session_id'] = $hosted_session_id;

        return $this;
    }

    /**
     * Gets id
     *
     * @return string|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string|null $id The ID for this request
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets insurance
     *
     * @return string|null
     */
    public function getInsurance()
    {
        return $this->container['insurance'];
    }

    /**
     * Sets insurance
     *
     * @param string|null $insurance This field can be used to pass through any character data that you may want returned unaltered for your own later usage
     *
     * @return self
     */
    public function setInsurance($insurance)
    {
        if (is_null($insurance)) {
            array_push($this->openAPINullablesSetToNull, 'insurance');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('insurance', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $allowedValues = $this->getInsuranceAllowableValues();
        if (!is_null($insurance) && !in_array($insurance, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'insurance', must be one of '%s'",
                    $insurance,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['insurance'] = $insurance;

        return $this;
    }

    /**
     * Gets internal_reference
     *
     * @return string|null
     */
    public function getInternalReference()
    {
        return $this->container['internal_reference'];
    }

    /**
     * Sets internal_reference
     *
     * @param string|null $internal_reference This field can be used to pass through any character data that you may want returned unaltered for your own later usage
     *
     * @return self
     */
    public function setInternalReference($internal_reference)
    {
        if (is_null($internal_reference)) {
            array_push($this->openAPINullablesSetToNull, 'internal_reference');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('internal_reference', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['internal_reference'] = $internal_reference;

        return $this;
    }

    /**
     * Gets log_request_id
     *
     * @return string|null
     */
    public function getLogRequestId()
    {
        return $this->container['log_request_id'];
    }

    /**
     * Sets log_request_id
     *
     * @param string|null $log_request_id An identifier for the API call that created this resource
     *
     * @return self
     */
    public function setLogRequestId($log_request_id)
    {
        if (is_null($log_request_id)) {
            array_push($this->openAPINullablesSetToNull, 'log_request_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('log_request_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['log_request_id'] = $log_request_id;

        return $this;
    }

    /**
     * Gets object_count
     *
     * @return int|null
     */
    public function getObjectCount()
    {
        return $this->container['object_count'];
    }

    /**
     * Sets object_count
     *
     * @param int|null $object_count The count of objects in this request
     *
     * @return self
     */
    public function setObjectCount($object_count)
    {
        if (is_null($object_count)) {
            throw new \InvalidArgumentException('non-nullable object_count cannot be null');
        }
        $this->container['object_count'] = $object_count;

        return $this;
    }

    /**
     * Gets origin
     *
     * @return \Arta\Client\Model\RequestListItemsInnerOrigin|null
     */
    public function getOrigin()
    {
        return $this->container['origin'];
    }

    /**
     * Sets origin
     *
     * @param \Arta\Client\Model\RequestListItemsInnerOrigin|null $origin origin
     *
     * @return self
     */
    public function setOrigin($origin)
    {
        if (is_null($origin)) {
            throw new \InvalidArgumentException('non-nullable origin cannot be null');
        }
        $this->container['origin'] = $origin;

        return $this;
    }

    /**
     * Gets public_reference
     *
     * @return string|null
     */
    public function getPublicReference()
    {
        return $this->container['public_reference'];
    }

    /**
     * Sets public_reference
     *
     * @param string|null $public_reference A client defined name for the resource. The value provided for the public_reference field may appear in notification emails and public web pages
     *
     * @return self
     */
    public function setPublicReference($public_reference)
    {
        if (is_null($public_reference)) {
            array_push($this->openAPINullablesSetToNull, 'public_reference');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('public_reference', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['public_reference'] = $public_reference;

        return $this;
    }

    /**
     * Gets quote_types
     *
     * @return string[]|null
     */
    public function getQuoteTypes()
    {
        return $this->container['quote_types'];
    }

    /**
     * Sets quote_types
     *
     * @param string[]|null $quote_types The IDs of the quote types generated for this request
     *
     * @return self
     */
    public function setQuoteTypes($quote_types)
    {
        if (is_null($quote_types)) {
            throw new \InvalidArgumentException('non-nullable quote_types cannot be null');
        }
        $allowedValues = $this->getQuoteTypesAllowableValues();
        if (array_diff($quote_types, $allowedValues)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'quote_types', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['quote_types'] = $quote_types;

        return $this;
    }

    /**
     * Gets shortcode
     *
     * @return string|null
     */
    public function getShortcode()
    {
        return $this->container['shortcode'];
    }

    /**
     * Sets shortcode
     *
     * @param string|null $shortcode A brief string identifier for this shipment
     *
     * @return self
     */
    public function setShortcode($shortcode)
    {
        if (is_null($shortcode)) {
            throw new \InvalidArgumentException('non-nullable shortcode cannot be null');
        }
        $this->container['shortcode'] = $shortcode;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string|null
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string|null $status The status for this shipment
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        $allowedValues = $this->getStatusAllowableValues();
        if (!in_array($status, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'status', must be one of '%s'",
                    $status,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets updated_at
     *
     * @return string|null
     */
    public function getUpdatedAt()
    {
        return $this->container['updated_at'];
    }

    /**
     * Sets updated_at
     *
     * @param string|null $updated_at A NaiveDatetime-formatted timestamp describing when the resource was last updated with microsecond precision
     *
     * @return self
     */
    public function setUpdatedAt($updated_at)
    {
        if (is_null($updated_at)) {
            throw new \InvalidArgumentException('non-nullable updated_at cannot be null');
        }
        $this->container['updated_at'] = $updated_at;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


